export interface MakeupSolution {
  slug: string;
  icon: string;
  title: string;
  desc: string;
  difficulty: "Kolay" | "Orta" | "İleri";
  duration: string;
  skinTypes?: string[];
  tools: string[];
  steps: { title: string; detail: string }[];
  tips: string[];
  productTypes: string[];
}

export const MAKEUP_SOLUTIONS: MakeupSolution[] = [
  {
    slug: "goz-alti-morluklari",
    icon: "🌙",
    title: "Göz Altı Morlukları",
    desc: "Renk düzeltme ve kapatıcı teknikleri",
    difficulty: "Orta",
    duration: "5-10 dk",
    skinTypes: ["Tüm Ciltler"],
    tools: ["Kapatıcı fırçası", "Güzellik süngeri", "Şeffaf pudra"],
    steps: [
      { title: "Göz altını nemlendirin", detail: "Göz kremi ile göz altını besleyin. Kuruluk kapatıcının çatlamasına neden olur." },
      { title: "Renk düzeltici uygulayın", detail: "Mor-mavi morluklar için şeftali/turuncu tonlu düzeltici; kahverengi morluklar için pembe düzeltici kullanın." },
      { title: "Kapatıcıyı uygulayın", detail: "Cildinizden 1-2 ton açık kapatıcıyı ters üçgen şeklinde göz altına noktalar halinde bırakın." },
      { title: "Süngerle yedirin", detail: "Nemli güzellik süngeri ile hafifçe bastırarak yedirin. Ovalamayın." },
      { title: "Şeffaf pudra ile sabitleyin", detail: "Az miktarda şeffaf pudrayı fırçayla göz altına hafifçe uygulayın. Aşırı pudra kırışıklık yapar." },
    ],
    tips: [
      "Kapatıcıyı uygulamadan önce 30 saniye bekleyin",
      "Işıltılı kapatıcı morluk üzerinde ters etki yapar",
      "Gece yeterli uyku ve su tüketimi farkı azaltır",
    ],
    productTypes: ["Renk Düzeltici", "Kapatıcı", "Şeffaf Pudra", "Göz Kremi"],
  },
  {
    slug: "akne-kapatma",
    icon: "🫧",
    title: "Akne & Sivilce Kapatma",
    desc: "Sivilceleri doğal şekilde gizle",
    difficulty: "Orta",
    duration: "5-8 dk",
    skinTypes: ["Yağlı", "Karma"],
    tools: ["İnce kapatıcı fırçası", "Güzellik süngeri", "Sabitleyici sprey"],
    steps: [
      { title: "Cildi hazırlayın", detail: "Temiz cilde nemlendirici ve primer uygulayın. Sivilce üzerinde salisilik asit bazlı ürün kullanabilirsiniz." },
      { title: "Yeşil renk düzeltici kullanın", detail: "Kırmızı sivilcelerin üzerine yeşil tonlu renk düzeltici noktalar halinde uygulayın." },
      { title: "Kapatıcıyı katman katman uygulayın", detail: "Cilt tonunuzla eşleşen mat kapatıcıyı ince katmanlar halinde uygulayın. Tek kalın katman yerine birkaç ince katman daha doğal durur." },
      { title: "Parmakla bastırarak yedirin", detail: "Fırça yerine temiz parmağınızla hafifçe bastırarak yedirin. Vücut ısısı ürünü eritip doğal gösterir." },
      { title: "Pudra ile sabitleyin", detail: "Mineral pudra veya sabitleyici pudrayı sivilce bölgesine uygulayın." },
    ],
    tips: [
      "Mat formüller sivilce üzerinde daha iyi durur",
      "Fırça kullanmak sivilceyi tahriş edebilir, parmak tercih edin",
      "Makyaj öncesi buz uygulaması kızarıklığı azaltır",
    ],
    productTypes: ["Yeşil Renk Düzeltici", "Mat Kapatıcı", "Mineral Pudra", "Sabitleyici Sprey"],
  },
  {
    slug: "genis-gozenekler",
    icon: "🔬",
    title: "Geniş Gözenekler",
    desc: "Gözenekleri minimize etme yolları",
    difficulty: "Kolay",
    duration: "3-5 dk",
    skinTypes: ["Yağlı", "Karma"],
    tools: ["Primer", "Güzellik süngeri", "Sabitleyici sprey"],
    steps: [
      { title: "Cildi temizleyip nemlendirin", detail: "Yağsız nemlendirici ile cildi hazırlayın. Yağlı formüller gözenekleri daha belirgin yapar." },
      { title: "Gözenek doldurucu primer uygulayın", detail: "Silikon bazlı primer gözenekleri doldurarak pürüzsüz bir yüzey oluşturur. T bölgesine odaklanın." },
      { title: "Fondöteni ince uygulayın", detail: "Hafif ile orta kapatıcılıkta mat fondöteni güzellik süngeri ile yedirin. Kalın tabaka gözeneklere yerleşir." },
      { title: "Sabitleyici sprey kullanın", detail: "Makyajı sabitleyin. Pudra gözeneklerde birikeceğinden spreyi tercih edin." },
    ],
    tips: [
      "Silikon bazlı primer gözenek görünümünü %50 azaltır",
      "Toz pudra yerine sabitleyici sprey tercih edin",
      "BHA (Salisilik Asit) düzenli kullanım gözenekleri küçültür",
    ],
    productTypes: ["Gözenek Doldurucu Primer", "Mat Fondöten", "Sabitleyici Sprey"],
  },
  {
    slug: "kizariklik-rozasea",
    icon: "🩹",
    title: "Kızarıklık & Rozasea",
    desc: "Kızarıklığı dengeleyen teknikler",
    difficulty: "Orta",
    duration: "8-12 dk",
    skinTypes: ["Hassas", "Kuru"],
    tools: ["Yumuşak fırça", "Güzellik süngeri", "Sabitleyici sprey"],
    steps: [
      { title: "Yatıştırıcı primer uygulayın", detail: "Yeşil tonlu veya yatıştırıcı primer kızarık bölgelere uygulayın. Hassas ciltler için parfümsüz ürün seçin." },
      { title: "Yeşil renk düzeltici kullanın", detail: "Kızarık bölgelere yeşil düzeltici uygulayın. Tüm yüze değil, sadece kızarık alanlara." },
      { title: "Mineral fondöten uygulayın", detail: "Mineral fondöten hassas ciltler için ideal. Nemli süngerle ince katman halinde uygulayın." },
      { title: "Allık dikkatli seçin", detail: "Pembe yerine şeftali tonlu allık tercih edin. Kızarık bölgelerden kaçının, yanaklarının en yüksek noktasına uygulayın." },
      { title: "Sabitleyicile son verin", detail: "Termal su spreyi veya yatıştırıcı sabitleyici ile makyajı sabitleyin." },
    ],
    tips: [
      "Hassas ciltler için parfümsüz ürünler şart",
      "Kırmızı ve turuncu tonlardan kaçının",
      "Fırça yerine sünger daha az tahriş eder",
    ],
    productTypes: ["Yeşil Primer", "Mineral Fondöten", "Şeftali Allık", "Termal Su"],
  },
  {
    slug: "yuz-sekillendirme",
    icon: "💎",
    title: "Yüz Şekillendirme",
    desc: "Kontur ve aydınlatıcı rehberi",
    difficulty: "İleri",
    duration: "10-15 dk",
    skinTypes: ["Tüm Ciltler"],
    tools: ["Kontur fırçası", "Fan fırça", "Güzellik süngeri", "Aydınlatıcı"],
    steps: [
      { title: "Yüz şeklinizi belirleyin", detail: "Oval, yuvarlak, kare, kalp veya uzun: her yüz şeklinin farklı kontur haritası vardır." },
      { title: "Kontur uygulayın", detail: "Cildinizden 2-3 ton koyu ürünü şakaklar, çene hattı ve burun kenarlarına uygulayın." },
      { title: "Aydınlatıcı uygulayın", detail: "Alın ortası, burun sırtı, elmacık kemikleri ve çene ucuna açık ton uygulayın." },
      { title: "İyice yedirin", detail: "Geçiş çizgisi kalmayana dek nemli süngerle yedirin. Doğal görünüm için yedirme çok önemli." },
      { title: "Highlighter ekleyin", detail: "Elmacık kemiklerinin en yüksek noktasına, burun ucuna ve cupid's bow'a hafif ışıltı ekleyin." },
    ],
    tips: [
      "Gün ışığında kontrol edin, çizgiler görünmemeli",
      "Krem ürünler doğal, toz ürünler belirgin sonuç verir",
      "Başlangıçta az ürünle başlayın, gerekirse ekleyin",
    ],
    productTypes: ["Kontur Paleti", "Aydınlatıcı", "Highlighter", "Kontur Fırçası"],
  },
  {
    slug: "yas-belirtileri",
    icon: "🪄",
    title: "Yaş Belirtileri",
    desc: "Gençleştiren makyaj ipuçları",
    difficulty: "Orta",
    duration: "10-15 dk",
    skinTypes: ["Kuru", "Olgun"],
    tools: ["Nemli sünger", "Yumuşak fırçalar", "Aydınlatıcı"],
    steps: [
      { title: "İyi nemlendirin", detail: "Hyaluronik asit içeren serum + nemlendirici ile cildi dolgunlaştırın. Kuru cilt kırışıklıkları vurgular." },
      { title: "Işıltılı primer kullanın", detail: "Işık yansıtan primer ile cildi parlak ve genç gösterin. Mat primerden kaçının." },
      { title: "Hafif fondöten seçin", detail: "Krem fondöten veya BB krem tercih edin. Kalın fondöten kırışıklıklara oturur." },
      { title: "Kremsi ürünler tercih edin", detail: "Allık ve far olarak kremsi formüller seçin. Toz ürünler ince çizgilere yerleşir." },
      { title: "Dudaklara dikkat edin", detail: "Dudak kalemi ile çerçeveleyip kremsi ruj uygulayın. Mat ruj dudakları kurutur ve ince gösterir." },
    ],
    tips: [
      "Mat ürünler yaşı vurgular, saten/parlak bitişler gençleştirir",
      "Göz altı kapatıcıyı çok fazla uygulamayın",
      "Dudak çevresi ince çizgilere primer uygulayın",
    ],
    productTypes: ["Nemlendirici Primer", "BB Krem", "Kremsi Allık", "Kremsi Ruj"],
  },
  {
    slug: "esit-olmayan-cilt-tonu",
    icon: "🎪",
    title: "Eşit Olmayan Cilt Tonu",
    desc: "Ton eşitleme teknikleri",
    difficulty: "Orta",
    duration: "8-10 dk",
    skinTypes: ["Tüm Ciltler"],
    tools: ["Güzellik süngeri", "Renk düzeltici", "Fondöten"],
    steps: [
      { title: "Renk haritası çıkarın", detail: "Yüzünüzdeki farklı tonları belirleyin: kızarık, sarımsı, koyu lekeler gibi." },
      { title: "Bölgesel renk düzeltme yapın", detail: "Kızarıklık → yeşil, koyu lekeler → şeftali/turuncu, sarımsı ton → lavanta düzeltici." },
      { title: "Orta kapatıcılıkta fondöten uygulayın", detail: "Tek seferde tam kapatma yerine katman katman uygulayın. İhtiyaç olan bölgelere ekstra katman ekleyin." },
      { title: "Kapatıcı ile noktasal düzeltme", detail: "Fondöten sonrası hâlâ görünen lekelere kapatıcı ile noktasal müdahale yapın." },
      { title: "Pudra ve sprey ile sabitleyin", detail: "Hafif pudra + sabitleyici sprey kombinasyonu ile bitirin." },
    ],
    tips: [
      "SPF düzenli kullanım lekeleri önler",
      "Niacinamide serumu ton eşitsizliğini azaltır",
      "Fondöteni doğal ışıkta test edin",
    ],
    productTypes: ["Renk Düzeltici Set", "Orta Kapatıcı Fondöten", "Kapatıcı", "Sabitleyici"],
  },
  {
    slug: "ince-dudaklar",
    icon: "💋",
    title: "İnce Dudaklar",
    desc: "Dudakları dolgun gösterme",
    difficulty: "Kolay",
    duration: "3-5 dk",
    skinTypes: ["Tüm Ciltler"],
    tools: ["Dudak kalemi", "Ruj", "Lip gloss"],
    steps: [
      { title: "Dudakları nemlendirin", detail: "Dudak peelingi veya balm ile dudakları yumuşatın. Pürüzsüz dudaklar dolgun görünür." },
      { title: "Dudak kalemi ile çerçeveleyin", detail: "Doğal dudak çizginizin 1mm dışından çizin. Daha fazlası yapay görünür. Ruj tonunuzla eşleşen kalem seçin." },
      { title: "İçini doldurun", detail: "Dudak kalemi ile dudağın içini tamamen doldurun. Bu ruj kalıcılığını artırır." },
      { title: "Ruj uygulayın", detail: "Kremsi veya saten bitişli ruj uygulayın. Mat ruj ince dudakları daha ince gösterir." },
      { title: "Gloss ile dolgunlaştırın", detail: "Dudağın ortasına şeffaf veya ışıltılı gloss uygulayın. Işık yansıması dolgunluk illüzyonu yaratır." },
    ],
    tips: [
      "Açık tonlar dudakları büyük, koyu tonlar küçük gösterir",
      "Dudağın ortasına açık ton uygulama dolgunluk verir",
      "Mentollü/biberli lip plumper geçici dolgunluk sağlar",
    ],
    productTypes: ["Dudak Kalemi", "Kremsi Ruj", "Lip Gloss", "Lip Plumper"],
  },
  // === YENİ ÇÖZÜMLER ===
  {
    slug: "smokey-eye",
    icon: "🖤",
    title: "Smokey Eye",
    desc: "Klasik dumanlı göz makyajı",
    difficulty: "İleri",
    duration: "15-20 dk",
    skinTypes: ["Tüm Ciltler"],
    tools: ["Far paleti", "Yedirme fırçası", "Göz kalemi", "Maskara"],
    steps: [
      { title: "Göz kapağına primer uygulayın", detail: "Göz farı primeri makyajın kalıcılığını artırır ve renklerin canlı görünmesini sağlar." },
      { title: "Geçiş tonunu uygulayın", detail: "Orta tonlu mat bir far ile göz çukuruna geçiş tonu uygulayın. Bu derinlik yaratır." },
      { title: "Koyu tonu ekleyin", detail: "Koyu rengi göz kapağının dış köşesine ve alt kirpik dibine uygulayın. V şekli oluşturun." },
      { title: "İyice yedirin", detail: "Yedirme fırçası ile sınırları yumuşatın. Smokey eye'da sert çizgi olmamalı." },
      { title: "Aydınlık ton ekleyin", detail: "İç göz köşesine ve kaş altına açık ışıltılı ton uygulayın. Gözü açar." },
      { title: "Eyeliner ve maskara ile bitirin", detail: "Kirpik dibine siyah kalem çekin ve bol maskara uygulayın." },
    ],
    tips: [
      "Altına şeffaf pudra serpin, dökülen farı temizlemek kolay olur",
      "Kahverengi tonlar daha gündüz, siyah daha gece uygun",
      "Alt göz kapağını ihmal etmeyin, bütünlük sağlar",
    ],
    productTypes: ["Far Paleti", "Göz Farı Primeri", "Yedirme Fırçası", "Maskara"],
  },
  {
    slug: "dogal-no-makeup",
    icon: "🌿",
    title: "No-Makeup Makeup",
    desc: "Doğal ama bakımlı görünüm",
    difficulty: "Kolay",
    duration: "5-8 dk",
    skinTypes: ["Tüm Ciltler"],
    tools: ["BB krem", "Kaş jeli", "Dudak balm", "Maskara"],
    steps: [
      { title: "Cildi iyi nemlendirin", detail: "İyi nemlenen cilt doğal makyajın temelidir. Serum + nemlendirici uygulayın." },
      { title: "BB krem veya tinted moisturizer sürün", detail: "Parmakla hafifçe yayarak doğal bir kaplama elde edin. Kapatıcılık düşük olmalı." },
      { title: "Kaşları şekillendirin", detail: "Şeffaf veya renkli kaş jeli ile kaşları doğal şekilde tarayın." },
      { title: "Yanakları renklendirin", detail: "Kremsi allık veya dudak-yanak ürünü ile yanakları hafifçe renklendirin." },
      { title: "Dudaklara renk verin", detail: "Renkli dudak balm veya lip tint ile doğal bir renk ekleyin." },
      { title: "Maskara sürün", detail: "Sadece üst kirpiklere bir kat kahverengi veya siyah maskara." },
    ],
    tips: [
      "Daha az ürün daha iyi sonuç verir",
      "Kremsi formüller toz ürünlere göre daha doğal durur",
      "Cilt bakımına yatırım yapın, az makyaj yeter",
    ],
    productTypes: ["BB Krem", "Kremsi Allık", "Kaş Jeli", "Lip Tint"],
  },
  {
    slug: "kas-sekillendirme",
    icon: "🪮",
    title: "Kaş Şekillendirme",
    desc: "Yüzü çerçeveleyen kaş teknikleri",
    difficulty: "Orta",
    duration: "5-10 dk",
    skinTypes: ["Tüm Ciltler"],
    tools: ["Kaş kalemi", "Kaş fırçası", "Kaş jeli", "Kapatıcı"],
    steps: [
      { title: "Doğal kaş şeklinizi analiz edin", detail: "Burun kenarından düz çekilen çizgi kaşın başlangıcını, burun kenarından göz bebeği üzerinden çekilen çizgi tepesini, burun kenarından göz dış köşesinden çekilen çizgi bitişini belirler." },
      { title: "Boşlukları doldurun", detail: "İnce kaş kalemi ile tüy benzeri kısa çizgiler çekerek seyrek bölgeleri doldurun." },
      { title: "Fırça ile yedirin", detail: "Kaş fırçası (spoolie) ile rengi yedirip doğal bir geçiş oluşturun." },
      { title: "Kaş jeli ile sabitleyin", detail: "Şeffaf veya renkli kaş jeli ile kaşları yerinde tutun." },
      { title: "Kaş altını temizleyin", detail: "İnce kapatıcı fırçası ile kaş altına kapatıcı sürerek keskin ve temiz bir hat oluşturun." },
    ],
    tips: [
      "Saç renginizden 1-2 ton açık kaş ürünü daha doğal durur",
      "Kaşın başını asla çok keskin yapmayın, yumuşak bırakın",
      "Sabun kaş tekniği dolgun görünüm için mükemmel",
    ],
    productTypes: ["Kaş Kalemi", "Kaş Jeli", "Kaş Pomadı", "Kaş Fırçası"],
  },
  {
    slug: "eyeliner-teknikleri",
    icon: "🖋️",
    title: "Eyeliner Çekme",
    desc: "Mükemmel eyeliner teknikleri",
    difficulty: "İleri",
    duration: "5-10 dk",
    skinTypes: ["Tüm Ciltler"],
    tools: ["Likit eyeliner", "Kalem eyeliner", "Bant", "Misel su"],
    steps: [
      { title: "Göz şeklinizi belirleyin", detail: "Badem, yuvarlak, kapak düşüklüğü, tek kapak: her göz şekline farklı eyeliner tekniği uyar." },
      { title: "Kuyruk açısını belirleyin", detail: "Alt kirpik çizgisinin devamı yönünde kuyruk çizin. Bant yapıştırarak rehber oluşturabilirsiniz." },
      { title: "İnce bir çizgiyle başlayın", detail: "Göz ortasından dışa doğru ince bir çizgi çekin. Kalınlığı sonra artırabilirsiniz." },
      { title: "İç köşeye doğru tamamlayın", detail: "Göz ortasından iç köşeye doğru incelerek çizgiyi tamamlayın." },
      { title: "Hataları düzeltin", detail: "Pamuklu çubuk ve misel su ile hataları temizleyin. Kapatıcı ile de düzeltebilirsiniz." },
    ],
    tips: [
      "Likit eyeliner keskin hat, kalem eyeliner yumuşak hat verir",
      "Gözü açık tutarak çizin, kapalı gözde hat farklı görünür",
      "Acemiyseniz kalem eyelinerla başlayın, affedicidir",
    ],
    productTypes: ["Likit Eyeliner", "Kalem Eyeliner", "Jel Eyeliner", "Misel Su"],
  },
  {
    slug: "allik-uygulama",
    icon: "🩰",
    title: "Allık Uygulama",
    desc: "Yüz şekline göre allık teknikleri",
    difficulty: "Kolay",
    duration: "2-5 dk",
    skinTypes: ["Tüm Ciltler"],
    tools: ["Allık fırçası", "Allık", "Güzellik süngeri"],
    steps: [
      { title: "Yüz şeklinizi belirleyin", detail: "Yuvarlak yüz: elmacık kemikleri boyunca yukarı. Uzun yüz: yanaklara yatay. Kalp yüz: elmacıkların altına." },
      { title: "Gülümseyin ve uygulayın", detail: "Gülümsediğinizde belirginleşen yanak toplarına uygulayın." },
      { title: "Yedirin", detail: "Fırça veya sünger ile sınırları yumuşatın. Sert renk geçişi olmamalı." },
      { title: "Katman ekleyin", detail: "Az ürünle başlayıp gerekirse katman ekleyin. Fazla allığı temizlemek zordur." },
    ],
    tips: [
      "Toz allık yağlı ciltlere, krem allık kuru ciltlere uygun",
      "Bronzer ile allığı karıştırmak doğal güneş öpmüş etki yaratır",
      "Allık rengini dudak rengine yakın seçin, uyumlu görünür",
    ],
    productTypes: ["Toz Allık", "Krem Allık", "Allık Paleti", "Allık Fırçası"],
  },
  {
    slug: "goz-fari-baslangic",
    icon: "🎨",
    title: "Göz Farı Başlangıç",
    desc: "Temel göz farı uygulama rehberi",
    difficulty: "Kolay",
    duration: "5-10 dk",
    skinTypes: ["Tüm Ciltler"],
    tools: ["Far paleti", "Düz fırça", "Yedirme fırçası", "Far primeri"],
    steps: [
      { title: "Far primeri uygulayın", detail: "Göz kapağına ince bir tabaka primer sürün. Farın kalıcılığını 2-3 kat artırır." },
      { title: "Açık tonu tüm kapağa sürün", detail: "Bej veya şampanya tonlu far ile tüm göz kapağını kaplayın. Bu baz görevi görür." },
      { title: "Orta tonu göz çukuruna uygulayın", detail: "Yedirme fırçası ile göz çukuruna orta tonlu far uygulayın. Derinlik yaratır." },
      { title: "Koyu tonu dış köşeye ekleyin", detail: "Dış V bölgesine koyu ton uygulayıp yedirin." },
      { title: "Işıltıyı iç köşeye ve kapak ortasına ekleyin", detail: "Parlak veya simli far ile iç köşeyi ve kapak merkezini aydınlatın." },
    ],
    tips: [
      "3 tonlu palet başlangıç için yeterli: açık, orta, koyu",
      "Yedirme en önemli adımdır, sert geçiş olmamalı",
      "Mat tonlar gündüz, simli tonlar gece için ideal",
    ],
    productTypes: ["Far Paleti", "Far Primeri", "Far Fırça Seti", "Göz Kalemi"],
  },
  {
    slug: "bronzlasma-efekti",
    icon: "☀️",
    title: "Bronzlaşma Efekti",
    desc: "Güneşten öpülmüş doğal görünüm",
    difficulty: "Kolay",
    duration: "5-8 dk",
    skinTypes: ["Tüm Ciltler"],
    tools: ["Bronzer", "Büyük fırça", "Highlighter"],
    steps: [
      { title: "Doğru bronzer tonu seçin", detail: "Cildinizden 1-2 ton koyu, sıcak tonlu bronzer seçin. Çok koyu bronzer çamurlu görünür." },
      { title: "3 bölgeye uygulayın", detail: "Güneşin doğal vurduğu yerler: alın kenarları, elmacık kemikleri altı ve çene hattı." },
      { title: "Boynunuza da sürün", detail: "Yüz-boyun uyumu için bronzeri boyun ve dekolteye de hafifçe uygulayın." },
      { title: "Highlighter ekleyin", detail: "Elmacık kemiklerinin tepesine, burun sırtına ve üst dudak ortasına highlighter sürün." },
    ],
    tips: [
      "Mat bronzer daha doğal, simli bronzer daha glamuröz",
      "Hafif katmanlar halinde uygulayın, fazlasını almak zordur",
      "Kış aylarında 1 ton açık bronzer tercih edin",
    ],
    productTypes: ["Bronzer", "Highlighter", "Büyük Pudra Fırçası", "Bronzlaştırıcı Damla"],
  },
  {
    slug: "kirpik-bakim",
    icon: "🦋",
    title: "Kirpik Teknikleri",
    desc: "Hacimli ve uzun kirpik sırları",
    difficulty: "Kolay",
    duration: "3-5 dk",
    skinTypes: ["Tüm Ciltler"],
    tools: ["Maskara", "Kirpik kıvırıcı", "Kirpik primeri"],
    steps: [
      { title: "Kirpikleri kıvırın", detail: "Kirpik kıvırıcı ile kök, orta ve uç olmak üzere 3 noktada bastırın. Maskaradan ÖNCE kıvırın." },
      { title: "Kirpik primeri uygulayın", detail: "Beyaz kirpik primeri hacim ve uzunluk ekler. Kurumadan maskara uygulayın." },
      { title: "Maskarayı zigzag hareketle sürün", detail: "Kökten uca zigzag yaparak sürün. Bu kirpikleri ayırır ve hacim verir." },
      { title: "Alt kirpiklere dikkat edin", detail: "Alt kirpiklere fırçayı dikey tutarak hafifçe sürün. Dağılmayı önler." },
    ],
    tips: [
      "Waterproof maskara kıvrımı daha uzun tutar",
      "İkinci kat maskarayı ilk kat kurumadan sürün",
      "Baby powder ile katmanlar arasına uygulama ekstra hacim verir",
    ],
    productTypes: ["Hacim Maskarası", "Uzatıcı Maskara", "Kirpik Kıvırıcı", "Kirpik Primeri"],
  },
  {
    slug: "yaglanma-kontrolu",
    icon: "🧊",
    title: "Yağlanma Kontrolü",
    desc: "Gün boyu mat kalma teknikleri",
    difficulty: "Kolay",
    duration: "5-8 dk",
    skinTypes: ["Yağlı", "Karma"],
    tools: ["Matlaştırıcı primer", "Pudra", "Yağ emici kağıt"],
    steps: [
      { title: "Cildi hafif nemlendirin", detail: "Yağsız, jel formlu nemlendirici kullanın. Nemlendirilmeyen yağlı cilt daha çok yağ üretir." },
      { title: "Matlaştırıcı primer uygulayın", detail: "T bölgesine (alın, burun, çene) matlaştırıcı primer uygulayın." },
      { title: "Yağsız fondöten seçin", detail: "Oil-free, mat bitişli fondöten kullanın. Güzellik süngeri ile yedirin." },
      { title: "Pudra ile sabitleyin", detail: "Transparan pudrayı T bölgesine hafifçe uygulayın. Aşırı pudra cake face yapar." },
      { title: "Gün içi bakım yapın", detail: "Yağ emici kağıtlar ile gün içi yağı bastırarak alın. Pudra eklemek yerine bunu tercih edin." },
    ],
    tips: [
      "Niacinamide serumu uzun vadede yağlanmayı azaltır",
      "Sabitleyici sprey pudra sonrası kalıcılığı artırır",
      "Makyaj üstü SPF spreyi kullanarak hem koruyun hem matlaştırın",
    ],
    productTypes: ["Matlaştırıcı Primer", "Oil-free Fondöten", "Transparan Pudra", "Yağ Emici Kağıt"],
  },
  {
    slug: "gelinlik-makyaji",
    icon: "👰",
    title: "Gelin Makyajı",
    desc: "Uzun süre dayanan özel gün makyajı",
    difficulty: "İleri",
    duration: "30-45 dk",
    skinTypes: ["Tüm Ciltler"],
    tools: ["Tam fırça seti", "Güzellik süngeri", "Sabitleyici sprey", "Takma kirpik"],
    steps: [
      { title: "Cildi önceden hazırlayın", detail: "Düğünden 1 hafta önce peeling, 1 gün önce nemlendirici maske yapın." },
      { title: "Uzun ömürlü baz oluşturun", detail: "Primer + uzun süre kalıcı fondöten + kapatıcı + pudra ile sağlam baz oluşturun." },
      { title: "Göz makyajını yapın", detail: "Waterproof ürünlerle göz makyajı yapın. Nötr ve romantik tonlar tercih edin." },
      { title: "Kontur ve aydınlatma", detail: "Hafif kontur ile yüzü şekillendirin, ışıltılı highlighter ile parlatın." },
      { title: "Dudak ve allık", detail: "Kalıcı ruj + dudak kalemi kombinasyonu. Allığı hafif ve romantik tutun." },
      { title: "Sabitleyici ile kilitleyin", detail: "Katman katman sabitleyici sprey uygulayın. Her aşamada spreyleyebilirsiniz." },
    ],
    tips: [
      "Düğün öncesi mutlaka deneme makyajı yapın",
      "Fotoğrafta beyaz yansıma yapan SPF ürünlerden kaçının",
      "Rötuş çantası hazırlayın: ruj, pudra, yağ emici kağıt, sabitleyici",
    ],
    productTypes: ["Kalıcı Fondöten", "Waterproof Maskara", "Sabitleyici Sprey", "Takma Kirpik"],
  },
  {
    slug: "ten-rengi-eslesme",
    icon: "🎯",
    title: "Fondöten Renk Eşleşme",
    desc: "Doğru fondöten tonu bulma rehberi",
    difficulty: "Kolay",
    duration: "5-10 dk",
    skinTypes: ["Tüm Ciltler"],
    tools: ["Fondöten örnekleri", "Doğal ışık"],
    steps: [
      { title: "Alt tonunuzu belirleyin", detail: "Bileklerinizin iç kısmına bakın: mavi damarlar = soğuk, yeşil damarlar = sıcak, karışık = nötr alt ton." },
      { title: "Çene hattında test edin", detail: "Fondöteni yüzünüze değil, çene hattına sürün. Yüz genelde boyundan farklı tondadır." },
      { title: "Doğal ışıkta kontrol edin", detail: "Mağazadaki yapay ışık yanıltır. Pencere kenarına veya dışarı çıkıp kontrol edin." },
      { title: "3 ton test edin", detail: "Tahmini tonunuz + 1 ton açık + 1 ton koyu deneyip en iyi eşleşeni seçin." },
      { title: "Boyunla uyumu kontrol edin", detail: "Doğru ton boyunla bütünleşir, yüzde maske etkisi yaratmaz." },
    ],
    tips: [
      "Yaz ve kış için 2 farklı ton fondöten bulundurun",
      "Mevsim geçişlerinde iki tonu karıştırarak kullanın",
      "Online alışverişte iade politikasını kontrol edin",
    ],
    productTypes: ["Fondöten", "BB Krem", "CC Krem", "Tinted Moisturizer"],
  },
  {
    slug: "dudak-bakimi",
    icon: "💋",
    title: "Dudak Bakımı & Makyaj",
    desc: "Kalıcı ve güzel dudak makyajı",
    difficulty: "Kolay",
    duration: "3-5 dk",
    skinTypes: ["Tüm Ciltler"],
    tools: ["Dudak peeling", "Dudak kalemi", "Ruj", "Kağıt mendil"],
    steps: [
      { title: "Dudakları peelinleyin", detail: "Şeker + bal karışımı veya dudak scrub ile ölü derileri temizleyin." },
      { title: "Nemlendirin", detail: "Dudak balm ile 5 dakika nemlendirin. Ruj öncesi silin." },
      { title: "Dudak kalemi ile çerçeveleyin", detail: "Ruj tonuna yakın dudak kalemi ile dudakları çerçeveleyin ve içini doldurun." },
      { title: "Ruj uygulayın", detail: "Fırça veya doğrudan ruj uygulayın." },
      { title: "Kağıt mendil tekniği", detail: "Bir kat ruj → kağıt mendil bastırın → ikinci kat ruj. Bu kalıcılığı 2 katına çıkarır." },
    ],
    tips: [
      "Mat rujlar daha kalıcı ama kurutucu, üstüne balm sürün",
      "Dudak çevresine kapatıcı sürme ruj dağılmasını önler",
      "Kırmızı ruj mavi alt tonlu ciltlere, turuncu kırmızı sıcak alt tonlara uyar",
    ],
    productTypes: ["Dudak Peeling", "Dudak Kalemi", "Mat Ruj", "Lip Stain"],
  },
  {
    slug: "hassas-cilt-makyaji",
    icon: "🪷",
    title: "Hassas Cilt Makyajı",
    desc: "Tahriş etmeyen makyaj seçimleri",
    difficulty: "Orta",
    duration: "10-15 dk",
    skinTypes: ["Hassas"],
    tools: ["Mineral makyaj ürünleri", "Yumuşak fırçalar", "Termal su"],
    steps: [
      { title: "Cildi yatıştırın", detail: "Centella veya aloe vera içeren nemlendirici uygulayın. Tahriş eden aktiflerden kaçının." },
      { title: "Hassas cilt primeri kullanın", detail: "Parfümsüz, silikon bazlı primer ile koruyucu bariyer oluşturun." },
      { title: "Mineral fondöten tercih edin", detail: "Mineral fondöten kimyasal katkısız olduğu için hassas ciltlere uygun. Fiziksel SPF de içerir." },
      { title: "Minimal ürün kullanın", detail: "Ne kadar az ürün, o kadar az tahriş riski. Sadece gerekli ürünleri uygulayın." },
      { title: "Termal su ile bitirin", detail: "Sabitleyici sprey yerine termal su spreyi ile makyajı ferahlatın." },
    ],
    tips: [
      "Yeni ürünleri kulak arkasında test edin, 24 saat bekleyin",
      "Parfümsüz ve hipoalerjenik ürünler tercih edin",
      "Makyaj fırçalarını haftada 1 yıkayın, bakteri birikimini önleyin",
    ],
    productTypes: ["Mineral Fondöten", "Hassas Cilt Primeri", "Termal Su", "Hipoalerjenik Maskara"],
  },
  {
    slug: "goz-kapagi-dusukluğu",
    icon: "👁️",
    title: "Göz Kapağı Düşüklüğü",
    desc: "Kapak düşüklüğüne uygun göz makyajı",
    difficulty: "Orta",
    duration: "8-12 dk",
    skinTypes: ["Tüm Ciltler"],
    tools: ["Far paleti", "Eyeliner", "Kirpik kıvırıcı", "Maskara"],
    steps: [
      { title: "Kapağı katlayarak çalışın", detail: "Gözler açıkken göz çukuru çizgisinin üstüne renk koyun. Kapalı gözde yapılan makyaj kapak arkasında kaybolur." },
      { title: "Koyu tonu doğru yerleştirin", detail: "Koyu far göz çukuru çizgisinin biraz üstüne uygulayın. Göz açıkken görünmeli." },
      { title: "Eyeliner tekniği", detail: "İnce eyeliner kullanın, kalın eyeliner kapağı daha düşük gösterir. Kuyrukta yukarı doğru çekin." },
      { title: "Kirpiklere odaklanın", detail: "Kirpik kıvırıcı + 2 kat maskara. Üst kirpikler yukarı baktığında göz açılır." },
      { title: "Kaş altını aydınlatın", detail: "Kaş kemiğinin altına mat açık far uygulayarak göz kapağını kaldırma illüzyonu yaratın." },
    ],
    tips: [
      "Waterproof formüller kapak katlanmasıyla bulaşmaz",
      "Alt göz kapağına koyu ton uygulamayın, gözü küçültür",
      "Takma kirpikler göz kapağını kaldırma etkisi yaratır",
    ],
    productTypes: ["Mat Far Paleti", "İnce Eyeliner", "Waterproof Maskara", "Kirpik Kıvırıcı"],
  },
  {
    slug: "makyaj-sabitleme",
    icon: "🛡️",
    title: "Makyaj Sabitleme",
    desc: "12+ saat kalıcı makyaj teknikleri",
    difficulty: "Kolay",
    duration: "3-5 dk",
    skinTypes: ["Yağlı", "Karma"],
    tools: ["Primer", "Sabitleyici pudra", "Sabitleyici sprey"],
    steps: [
      { title: "Doğru primer seçin", detail: "Yağlı cilt: matlaştırıcı primer. Kuru cilt: nemlendirici primer. Primer fondötenin tutunmasını sağlar." },
      { title: "İnce katmanlar halinde uygulayın", detail: "Kalın makyaj katmanları kayar. İnce katmanlar + aralarında sabitleme = kalıcı makyaj." },
      { title: "Stratejik pudralayın", detail: "Pudrayı sadece T bölgesine uygulayın. Tüm yüze pudra cake face yapar." },
      { title: "Sabitleyici sprey kullanın", detail: "Son dokunuş olarak sabitleyici sprey. Yüzden 20cm uzaktan X şeklinde sıkın." },
      { title: "Gün içi rötuş yapın", detail: "Yağ emici kağıt + sabitleyici sprey ile gün içi tazeleyin. Üstüne makyaj eklemeyin." },
    ],
    tips: [
      "Baking tekniği: pudrayı 5 dk bekletip silmek ekstra kalıcılık verir",
      "Sabitleyici sprey buzdolabında saklayın, serinliği gözenekleri sıkılaştırır",
      "Yaz aylarında waterproof ürünler şart",
    ],
    productTypes: ["Sabitleyici Sprey", "Transparan Pudra", "Matlaştırıcı Primer", "Yağ Emici Kağıt"],
  },
  {
    slug: "glass-skin",
    icon: "",
    title: "Glass Skin (Cam Cilt)",
    desc: "Kore tarzı ışıltılı, pürüzsüz cilt efekti",
    difficulty: "Orta",
    duration: "15-20 dk",
    skinTypes: ["Kuru", "Normal", "Karma"],
    tools: ["Nemlendirici tonik", "Serum", "Dewy fondöten", "Highlighter"],
    steps: [
      { title: "Katmanlı nemlendirme yapın", detail: "Tonik → Essans → Serum → Nemlendirici. Her katmanı cildin emmesini bekleyin. Bu K-Beauty'nin '7 skin method' tekniğidir." },
      { title: "Işıltılı primer uygulayın", detail: "Strobe/illuminating primer ile cildi içeriden parlıyormuş gibi gösterin. Charlotte Tilbury Flawless Filter veya MAC Strobe Cream idealdir." },
      { title: "Dewy fondöten veya skin tint kullanın", detail: "Mat fondöten kullanmayın! Dewy/satin bitişli, ışık yansıtan fondöten tercih edin. Parmakla veya beauty blender ile yedirin." },
      { title: "Stratejik highlighter uygulayın", detail: "Likit highlighter'ı elmacık kemikleri, burun sırtı, cupid's bow ve çene ucuna uygulayın. Fan fırça ile yayın." },
      { title: "Yüz sisi ile sabitleyin", detail: "Dewy sabitleyici sprey veya gül suyu sıkın. Mat sprey kullanmayın, ışıltıyı söndürür." },
    ],
    tips: [
      "Glass skin'in sırrı cilt bakımıdır — makyajdan önce iyi nemlendirin",
      "Krem ürünler pudra ürünlerden daha iyi sonuç verir",
      "Yağ emici kağıt yerine sabitleyici sprey ile rötuş yapın",
    ],
    productTypes: ["Dewy Fondöten", "Işıltılı Primer", "Likit Highlighter", "Yüz Sisi Sprey"],
  },
  {
    slug: "fox-eye",
    icon: "",
    title: "Fox Eye (Tilki Göz)",
    desc: "Çekik göz efekti — trend makyaj tekniği",
    difficulty: "İleri",
    duration: "15-20 dk",
    skinTypes: ["Tüm Ciltler"],
    tools: ["Eyeliner", "Far paleti", "Kaş jeli", "Kirpik kıvırıcı"],
    steps: [
      { title: "Kaşları yukarı tarayın", detail: "Kaş jelini kullanarak kaşları tamamen yukarı doğru tarayın ve sabitleyın. Bu gözü optik olarak yukarı çeker." },
      { title: "Göz kapağına açık ton far uygulayın", detail: "Kapağa mat açık tonlu far uygulayın. Kırışıklık hattının üstüne daha koyu ton ile geçiş yapın." },
      { title: "Wing eyeliner çizin", detail: "Eyeliner'ı göz ucundan şakağa doğru yukarı çekin. Çizgi kalın değil, ince ve uzun olmalı. Alt göz ucundan da ince bir çizgi çekin." },
      { title: "İç köşeyi derinleştirin", detail: "Göz iç köşesine koyu ton far veya eyeliner ile hafif gölge ekleyin. Bu gözleri daha çekik gösterir." },
      { title: "Dış köşe kirpiklere odaklanın", detail: "Maskarayı dış köşeye yoğunlaştırın veya yarım kirpik takın. Dış köşe vurgusu tilki göz efektini tamamlar." },
    ],
    tips: [
      "Bant yöntemi ile eyeliner çizgisini düzgün çekin",
      "Alt göz kapağına koyu çizgi çekmek gözü küçültebilir — dikkatli olun",
      "Trend alternatifi: Doe Eye (ceylan göz) daha yumuşak bir versiyon",
    ],
    productTypes: ["Jel Eyeliner", "Mat Far Paleti", "Sabitleyici Kaş Jeli", "Yarım Takma Kirpik"],
  },
  {
    slug: "clean-girl",
    icon: "",
    title: "Clean Girl Makyajı",
    desc: "Minimal, sağlıklı ve bakımlı görünüm",
    difficulty: "Kolay",
    duration: "10-15 dk",
    skinTypes: ["Tüm Ciltler"],
    tools: ["Skin tint", "Krem allık", "Lip gloss", "Kaş jeli"],
    steps: [
      { title: "Cildi hazırlayın ve skin tint uygulayın", detail: "İyi nemlendirin, SPF sürün. Fondöten yerine skin tint veya BB krem kullanın. Sadece gerekli yerlere kapatıcı." },
      { title: "Kaşları tarayıp sabitleyin", detail: "Şeffaf veya renkli kaş jeli ile kaşları yukarı doğru tarayın. Soap brows tekniği ile lamination efekti verin." },
      { title: "Krem allık uygulayın", detail: "Elmacık kemiklerine pembe veya şeftali tonlu krem allık. Parmakla dağıtın — doğal kızarıklık efekti." },
      { title: "Dudaklara balm veya gloss", detail: "Lip balm veya hafif renkli lip gloss. Nude tonlar tercih edin. Dior Lip Glow veya NYX Butter Gloss idealdir." },
      { title: "Bir kat maskara", detail: "Sadece üst kirpiklere bir kat maskara. Alt kirpikleri atlamak daha minimal görünüm verir." },
    ],
    tips: [
      "Clean girl'ün sırrı iyi cilt bakımıdır — makyajla kapamak değil",
      "Parlak, sağlıklı cilt için önceden hyaluronik asit serum uygulayın",
      "Saç: düşük topuz veya slick back at kuyruğu ile tamamlayın",
    ],
    productTypes: ["Skin Tint", "Krem Allık", "Lip Gloss", "Şeffaf Kaş Jeli"],
  },
  {
    slug: "sunset-eye",
    icon: "",
    title: "Sunset Eye (Gün Batımı Göz)",
    desc: "Turuncu, kırmızı, sarı tonlarla sıcak göz makyajı",
    difficulty: "Orta",
    duration: "15-20 dk",
    skinTypes: ["Tüm Ciltler"],
    tools: ["Renkli far paleti", "Fırça seti", "Primer", "Maskara"],
    steps: [
      { title: "Göz primerı uygulayın", detail: "Far primerı göz kapağına uygulayarak renklerin daha canlı ve kalıcı olmasını sağlayın." },
      { title: "Sarı tonu iç köşeye yerleştirin", detail: "Parlak sarı tonu göz iç köşesine ve kapağın iç yarısına parmakla veya flat fırça ile bastırarak uygulayın." },
      { title: "Turuncu ile geçiş yapın", detail: "Kapağın ortasına turuncu ton ekleyin. Blending fırçası ile sarı-turuncu geçişini yumuşatın." },
      { title: "Dış köşeye kırmızı/bordo ekleyin", detail: "Dış V bölgesine kırmızı veya bordo ton ekleyin. Kırışıklık çizgisinin üstüne doğru yayın. Blend edin." },
      { title: "Alt çizgiyi tamamlayın", detail: "Alt kirpik dibine aynı renk sırasını hafifçe uygulayın. İnce eyeliner veya kahverengi göz kalemi ekleyin." },
    ],
    tips: [
      "Morphe 35O, Huda Beauty Neon Orange veya NYX Ultimate Brights paleti idealdir",
      "Göz altına düşebilecek pigment için önceden pudra uygulayın veya sonra temizleyin",
      "Bu makyajla dudak tonunu nude tutun — göz odak noktası olsun",
    ],
    productTypes: ["Renkli Far Paleti", "Göz Primerı", "Blending Fırçası", "Waterproof Maskara"],
  },
  {
    slug: "lamination-kas",
    icon: "",
    title: "Kaş Laminasyonu Efekti",
    desc: "Evde profesyonel kaş laminasyonu görünümü",
    difficulty: "Kolay",
    duration: "5-8 dk",
    skinTypes: ["Tüm Ciltler"],
    tools: ["Kaş sabunu/jeli", "Spoolie fırça", "Kaş kalemi", "Kapatıcı"],
    steps: [
      { title: "Kaş sabununu ıslatın", detail: "Soap brows tekniği: kaş sabununu veya şeffaf kaş jelini spoolie fırçaya alın. Hafifçe nemlendirin." },
      { title: "Kaşları yukarı doğru tarayın", detail: "Tüm kaş kıllarını yukarı doğru tarayarak sabitleyin. Ark bölgesindeki kılları hafifçe yana yönlendirin." },
      { title: "Seyrek bölgeleri doldurun", detail: "İnce uçlu kaş kalemi ile kaş kılı taklidi yaparak seyrek bölgeleri doldurun. Darbeler halinde, kıl yönünde çizin." },
      { title: "Kapatıcı ile şekillendirin", detail: "İnce kapatıcı fırçası ile kaş alt ve üst sınırına kapatıcı uygulayın. Bu kaşları daha keskin ve tanımlı gösterir." },
    ],
    tips: [
      "Pears sabunu veya Got2b Glued jel düşük maliyetli soap brows alternatifidir",
      "Kaşları kestirirken alt sıranın doğal formunu bozmayın",
      "Sabitleme için son kat şeffaf kaş jeli sıkın",
    ],
    productTypes: ["Kaş Sabunu", "İnce Kaş Kalemi", "Şeffaf Kaş Jeli", "Kapatıcı"],
  },
  {
    slug: "douyin-makyaj",
    icon: "",
    title: "Douyin (TikTok) Makyajı",
    desc: "Çin viral makyaj trendi — dramatik dönüşüm",
    difficulty: "İleri",
    duration: "25-35 dk",
    skinTypes: ["Tüm Ciltler"],
    tools: ["Full coverage fondöten", "Kontur kiti", "Takma kirpik", "Renkli lens"],
    steps: [
      { title: "Kusursuz baz oluşturun", detail: "Full coverage fondöten + kapatıcı ile kusursuz bir tuval oluşturun. Gözenekler ve imperfections tamamen kapatılmalı." },
      { title: "Dramatik kontur yapın", detail: "Burun yanlarını daraltın, çene hattını belirginleştirin, elmacık kemiklerini yükseltin. Douyin makyajın temeli güçlü konturdur." },
      { title: "Büyük göz efekti yaratın", detail: "Alt göz kapağına beyaz veya açık ton far uygulayın. Göz bebeğinin altına beyaz eyeliner çekin. Bu göz boyutunu optik büyütür." },
      { title: "Eyeliner ve takma kirpik", detail: "Kalın wing eyeliner + yoğun takma kirpik takın. Alt kirpik dibine de ince eyeliner çekin." },
      { title: "Ombre dudak uygulayın", detail: "Dudağın ortasına kırmızı ruj, dış kenarlara kapatıcı ile gradient efekti verin. K-style ombre lip." },
    ],
    tips: [
      "Renkli lens dramatik etkiyi artırır (günlük kullanım değil)",
      "Burun konturunun gerçekçi görünmesi için blend çok önemli",
      "Bu makyaj fotoğraf/video için idealdir, günlük kullanımda abartılı görünebilir",
    ],
    productTypes: ["Full Coverage Fondöten", "Kontur Paleti", "Takma Kirpik", "Ombre Ruj"],
  },
  {
    slug: "latte-makyaj",
    icon: "",
    title: "Latte Makyajı",
    desc: "Sıcak kahve tonlarıyla doğal kahve esintili look",
    difficulty: "Kolay",
    duration: "12-18 dk",
    skinTypes: ["Tüm Ciltler"],
    tools: ["Kahverengi far paleti", "Bronzer", "Nude ruj", "Krem allık"],
    steps: [
      { title: "Sıcak tonlu baz uygulayın", detail: "Sıcak tonlu fondöten veya skin tint ile doğal bir baz oluşturun. Bronzer ile hafifçe sıcaklık ekleyin." },
      { title: "Kahve tonlu far uygulayın", detail: "Kapağa açık süt kahve, kırışıklık hattına orta kahve, dış köşeye koyu kahve uygulayın. Blend fırçası ile geçişleri yumuşatın." },
      { title: "Krem allık + bronzer kombinasyonu", detail: "Elmacık kemiklerine şeftali/terra cotta tonu krem allık, üstüne hafif bronzer. Sıcak, güneş öpmüş görünüm." },
      { title: "Nude-kahve dudak", detail: "Dudak kalemi ile sınırı çizin, nude-kahve tonlu ruj veya lip liner trick uygulayın. Ortaya hafif gloss." },
      { title: "Kahve maskarası ile bitirin", detail: "Siyah yerine kahverengi maskara daha yumuşak bir görünüm verir. Kaşları da kahverengi ile doldurun." },
    ],
    tips: [
      "Charlotte Tilbury Pillow Talk serisi bu look için idealdir",
      "NYX Butter Gloss Praline tonu dudak için mükemmel",
      "Sıcak tonlu ışıltılı highlighter ile tamamlayın (altın/şampanya)",
    ],
    productTypes: ["Kahve Tonlu Far Paleti", "Bronzer", "Nude Ruj", "Kahverengi Maskara"],
  },
  {
    slug: "monokrom-makyaj",
    icon: "",
    title: "Monokrom Makyajı",
    desc: "Tek renk paletinde uyumlu, şık makyaj",
    difficulty: "Kolay",
    duration: "10-15 dk",
    skinTypes: ["Tüm Ciltler"],
    tools: ["Çok amaçlı stik", "Far", "Ruj", "Allık"],
    steps: [
      { title: "Ana renginizi seçin", detail: "Pembe, şeftali, mercan, berry — bir ana ton seçin. Bu tonu göz, yanak ve dudakta kullanacaksınız." },
      { title: "Gözlere renk ekleyin", detail: "Seçtiğiniz tonda far uygulayın. Kapağa yoğun, kırışıklık hattına açık. Parmakla da uygulayabilirsiniz." },
      { title: "Yanakları renklendirin", detail: "Aynı renk ailesinden allık uygulayın. Krem allık en doğal sonucu verir." },
      { title: "Dudaklara son dokunuş", detail: "Yine aynı renk ailesinden ruj/lip tint uygulayın. Üç alanın renk uyumu monokrom büyüsünü yaratır." },
    ],
    tips: [
      "ILIA Multi-Stick veya Rare Beauty gibi çok amaçlı ürünler bu look için biçilmiş kaftan",
      "Sıcak tonlara şeftali/mercan, soğuk tonlara pembe/mauve tercih edin",
      "Bronzer ekleyerek boyut kazandırın — düz görünmesini önleyin",
    ],
    productTypes: ["Çok Amaçlı Stik", "Krem Allık", "Mat Ruj", "Tonlu Far"],
  },
  {
    slug: "badem-goz",
    icon: "",
    title: "Badem Göz Makyajı",
    desc: "Gözleri badem şekline getiren teknikler",
    difficulty: "Orta",
    duration: "12-18 dk",
    skinTypes: ["Tüm Ciltler"],
    tools: ["Jel eyeliner", "Far paleti", "Maskara", "Kaş ürünleri"],
    steps: [
      { title: "İç köşeye aydınlatıcı uygulayın", detail: "Göz iç köşesine açık renk ışıltılı far veya highlighter uygulayın. Gözü optik olarak açar." },
      { title: "Dış köşeye koyu tonla derinlik katın", detail: "Dış V bölgesine koyu kahve veya siyah mat far ile gölge verin. Yukarı doğru açılı çalışın." },
      { title: "Eyeliner ile şekil verin", detail: "Üst kirpik dibinden başlayıp dış köşeye doğru hafifçe kaldıran ince çizgi çekin. Wing yukarı doğru olmalı." },
      { title: "Alt göz kapağını tanımlayın", detail: "Alt kirpik dibinin dış 1/3'üne ince eyeliner veya koyu far uygulayın. İç tarafa kadar uzatmayın." },
      { title: "Maskarayı stratejik uygulayın", detail: "Dış köşe kirpiklerini daha fazla boyayın. Kirpik kıvırıcı ile önce kıvırın. Alt kirpiklere çok az uygulayın." },
    ],
    tips: [
      "Göz şeklinize göre eyeliner kalınlığını ayarlayın",
      "Yuvarlak gözlerde dış köşeyi uzatmak badem efektini güçlendirir",
      "Düşük göz kapağında eyeliner'ı gözler açıkken çizin — kapalıyken belli olmayabilir",
    ],
    productTypes: ["Jel Eyeliner", "Koyu Mat Far", "Işıltılı Far", "Hacimli Maskara"],
  },
  {
    slug: "strobing",
    icon: "",
    title: "Strobing (Aydınlatma)",
    desc: "Kontur yerine sadece ışıkla yüz şekillendirme",
    difficulty: "Kolay",
    duration: "8-12 dk",
    skinTypes: ["Normal", "Kuru", "Karma"],
    tools: ["Likit highlighter", "Fan fırça", "Işıltılı primer", "Dewy fondöten"],
    steps: [
      { title: "Işıltılı primer ile başlayın", detail: "Tüm yüze veya sadece yüksek noktalara illuminating primer uygulayın. MAC Strobe Cream veya Charlotte Tilbury Flawless Filter." },
      { title: "Dewy fondöten uygulayın", detail: "Mat fondöten kullanmayın. Dewy/luminous bitişli fondöten tercih edin. Bu strobing'in temelini oluşturur." },
      { title: "Likit highlighter'ı stratejik uygulayın", detail: "Elmacık kemikleri üstü, burun sırtı, cupid's bow, çene ucu, alın ortası — bu 5 nokta ışık yakalar." },
      { title: "Fan fırça ile yayın", detail: "Fan fırça ile highlighter'ı hafifçe yayarak doğal ışıltı elde edin. Parmak da kullanabilirsiniz." },
      { title: "Köprücük kemiklerine de ekleyin", detail: "Açık yaka giyiyorsanız köprücük kemiklerine de highlighter uygulayın. Vücut ışıltısı şıklık katar." },
    ],
    tips: [
      "Strobing yağlı ciltlerde parlaklığı artırabilir — T-bölgesini atlayın",
      "Sıcak tonlar için altın highlighter, soğuk tonlar için gümüş/pembe tercih edin",
      "Kontur yok, sadece ışık — daha doğal ve gençleştirici bir teknik",
    ],
    productTypes: ["Likit Highlighter", "Işıltılı Primer", "Dewy Fondöten", "Fan Fırça"],
  },
];
