export interface MakeupSolution {
  slug: string;
  icon: string;
  title: string;
  desc: string;
  difficulty: "Kolay" | "Orta" | "İleri";
  duration: string;
  tools: string[];
  steps: { title: string; detail: string }[];
  tips: string[];
  productTypes: string[];
}

export const MAKEUP_SOLUTIONS: MakeupSolution[] = [
  {
    slug: "goz-alti-morluklari",
    icon: "👁️",
    title: "Göz Altı Morlukları",
    desc: "Renk düzeltme ve kapatıcı teknikleri",
    difficulty: "Orta",
    duration: "5-10 dk",
    tools: ["Kapatıcı fırçası", "Güzellik süngeri", "Şeffaf pudra"],
    steps: [
      { title: "Göz altını nemlendirin", detail: "Göz kremi ile göz altını besleyin. Kuruluk kapatıcının çatlamasına neden olur." },
      { title: "Renk düzeltici uygulayın", detail: "Mor-mavi morluklar için şeftali/turuncu tonlu düzeltici; kahverengi morluklar için pembe düzeltici kullanın." },
      { title: "Kapatıcıyı uygulayın", detail: "Cildinizden 1-2 ton açık kapatıcıyı ters üçgen şeklinde göz altına noktalar halinde bırakın." },
      { title: "Süngerle yedirin", detail: "Nemli güzellik süngeri ile hafifçe bastırarak yedirin. Ovalamayın." },
      { title: "Şeffaf pudra ile sabitleyin", detail: "Az miktarda şeffaf pudrayı fırçayla göz altına hafifçe uygulayın. Aşırı pudra kırışıklık yapar." },
    ],
    tips: [
      "Kapatıcıyı uygulamadan önce 30 saniye bekleyin",
      "Işıltılı kapatıcı morluk üzerinde ters etki yapar",
      "Gece yeterli uyku ve su tüketimi farkı azaltır",
    ],
    productTypes: ["Renk Düzeltici", "Kapatıcı", "Şeffaf Pudra", "Göz Kremi"],
  },
  {
    slug: "akne-kapatma",
    icon: "🔴",
    title: "Akne & Sivilce Kapatma",
    desc: "Sivilceleri doğal şekilde gizle",
    difficulty: "Orta",
    duration: "5-8 dk",
    tools: ["İnce kapatıcı fırçası", "Güzellik süngeri", "Sabitleyici sprey"],
    steps: [
      { title: "Cildi hazırlayın", detail: "Temiz cilde nemlendirici ve primer uygulayın. Sivilce üzerinde salisilik asit bazlı ürün kullanabilirsiniz." },
      { title: "Yeşil renk düzeltici kullanın", detail: "Kırmızı sivilcelerin üzerine yeşil tonlu renk düzeltici noktalar halinde uygulayın." },
      { title: "Kapatıcıyı katman katman uygulayın", detail: "Cilt tonunuzla eşleşen mat kapatıcıyı ince katmanlar halinde uygulayın. Tek kalın katman yerine birkaç ince katman daha doğal durur." },
      { title: "Parmakla bastırarak yedirin", detail: "Fırça yerine temiz parmağınızla hafifçe bastırarak yedirin. Vücut ısısı ürünü eritip doğal gösterir." },
      { title: "Pudra ile sabitleyin", detail: "Mineral pudra veya sabitleyici pudrayı sivilce bölgesine uygulayın." },
    ],
    tips: [
      "Mat formüller sivilce üzerinde daha iyi durur",
      "Fırça kullanmak sivilceyi tahriş edebilir, parmak tercih edin",
      "Makyaj öncesi buz uygulaması kızarıklığı azaltır",
    ],
    productTypes: ["Yeşil Renk Düzeltici", "Mat Kapatıcı", "Mineral Pudra", "Sabitleyici Sprey"],
  },
  {
    slug: "genis-gozenekler",
    icon: "⭕",
    title: "Geniş Gözenekler",
    desc: "Gözenekleri minimize etme yolları",
    difficulty: "Kolay",
    duration: "3-5 dk",
    tools: ["Primer", "Güzellik süngeri", "Sabitleyici sprey"],
    steps: [
      { title: "Cildi temizleyip nemlendirin", detail: "Yağsız nemlendirici ile cildi hazırlayın. Yağlı formüller gözenekleri daha belirgin yapar." },
      { title: "Gözenek doldurucu primer uygulayın", detail: "Silikon bazlı primer gözenekleri doldurarak pürüzsüz bir yüzey oluşturur. T bölgesine odaklanın." },
      { title: "Fondöteni ince uygulayın", detail: "Hafif ile orta kapatıcılıkta mat fondöteni güzellik süngeri ile yedirin. Kalın tabaka gözeneklere yerleşir." },
      { title: "Sabitleyici sprey kullanın", detail: "Makyajı sabitleyin. Pudra gözeneklerde birikeceğinden spreyi tercih edin." },
    ],
    tips: [
      "Silikon bazlı primer gözenek görünümünü %50 azaltır",
      "Toz pudra yerine sabitleyici sprey tercih edin",
      "BHA (Salisilik Asit) düzenli kullanım gözenekleri küçültür",
    ],
    productTypes: ["Gözenek Doldurucu Primer", "Mat Fondöten", "Sabitleyici Sprey"],
  },
  {
    slug: "kizariklik-rozasea",
    icon: "🌹",
    title: "Kızarıklık & Rozasea",
    desc: "Kızarıklığı dengeleyen teknikler",
    difficulty: "Orta",
    duration: "8-12 dk",
    tools: ["Yumuşak fırça", "Güzellik süngeri", "Sabitleyici sprey"],
    steps: [
      { title: "Yatıştırıcı primer uygulayın", detail: "Yeşil tonlu veya yatıştırıcı primer kızarık bölgelere uygulayın. Hassas ciltler için parfümsüz ürün seçin." },
      { title: "Yeşil renk düzeltici kullanın", detail: "Kızarık bölgelere yeşil düzeltici uygulayın. Tüm yüze değil, sadece kızarık alanlara." },
      { title: "Mineral fondöten uygulayın", detail: "Mineral fondöten hassas ciltler için ideal. Nemli süngerle ince katman halinde uygulayın." },
      { title: "Allık dikkatli seçin", detail: "Pembe yerine şeftali tonlu allık tercih edin. Kızarık bölgelerden kaçının, yanaklarının en yüksek noktasına uygulayın." },
      { title: "Sabitleyicile son verin", detail: "Termal su spreyi veya yatıştırıcı sabitleyici ile makyajı sabitleyin." },
    ],
    tips: [
      "Hassas ciltler için parfümsüz ürünler şart",
      "Kırmızı ve turuncu tonlardan kaçının",
      "Fırça yerine sünger daha az tahriş eder",
    ],
    productTypes: ["Yeşil Primer", "Mineral Fondöten", "Şeftali Allık", "Termal Su"],
  },
  {
    slug: "yuz-sekillendirme",
    icon: "📐",
    title: "Yüz Şekillendirme",
    desc: "Kontur ve aydınlatıcı rehberi",
    difficulty: "İleri",
    duration: "10-15 dk",
    tools: ["Kontur fırçası", "Fan fırça", "Güzellik süngeri", "Aydınlatıcı"],
    steps: [
      { title: "Yüz şeklinizi belirleyin", detail: "Oval, yuvarlak, kare, kalp veya uzun: her yüz şeklinin farklı kontur haritası vardır." },
      { title: "Kontur uygulayın", detail: "Cildinizden 2-3 ton koyu ürünü şakaklar, çene hattı ve burun kenarlarına uygulayın." },
      { title: "Aydınlatıcı uygulayın", detail: "Alın ortası, burun sırtı, elmacık kemikleri ve çene ucuna açık ton uygulayın." },
      { title: "İyice yedirin", detail: "Geçiş çizgisi kalmayana dek nemli süngerle yedirin. Doğal görünüm için yedirme çok önemli." },
      { title: "Highlighter ekleyin", detail: "Elmacık kemiklerinin en yüksek noktasına, burun ucuna ve cupid's bow'a hafif ışıltı ekleyin." },
    ],
    tips: [
      "Gün ışığında kontrol edin, çizgiler görünmemeli",
      "Krem ürünler doğal, toz ürünler belirgin sonuç verir",
      "Başlangıçta az ürünle başlayın, gerekirse ekleyin",
    ],
    productTypes: ["Kontur Paleti", "Aydınlatıcı", "Highlighter", "Kontur Fırçası"],
  },
  {
    slug: "yas-belirtileri",
    icon: "✨",
    title: "Yaş Belirtileri",
    desc: "Gençleştiren makyaj ipuçları",
    difficulty: "Orta",
    duration: "10-15 dk",
    tools: ["Nemli sünger", "Yumuşak fırçalar", "Aydınlatıcı"],
    steps: [
      { title: "İyi nemlendirin", detail: "Hyaluronik asit içeren serum + nemlendirici ile cildi dolgunlaştırın. Kuru cilt kırışıklıkları vurgular." },
      { title: "Işıltılı primer kullanın", detail: "Işık yansıtan primer ile cildi parlak ve genç gösterin. Mat primerden kaçının." },
      { title: "Hafif fondöten seçin", detail: "Krem fondöten veya BB krem tercih edin. Kalın fondöten kırışıklıklara oturur." },
      { title: "Kremsi ürünler tercih edin", detail: "Allık ve far olarak kremsi formüller seçin. Toz ürünler ince çizgilere yerleşir." },
      { title: "Dudaklara dikkat edin", detail: "Dudak kalemi ile çerçeveleyip kremsi ruj uygulayın. Mat ruj dudakları kurutur ve ince gösterir." },
    ],
    tips: [
      "Mat ürünler yaşı vurgular, saten/parlak bitişler gençleştirir",
      "Göz altı kapatıcıyı çok fazla uygulamayın",
      "Dudak çevresi ince çizgilere primer uygulayın",
    ],
    productTypes: ["Nemlendirici Primer", "BB Krem", "Kremsi Allık", "Kremsi Ruj"],
  },
  {
    slug: "esit-olmayan-cilt-tonu",
    icon: "🎭",
    title: "Eşit Olmayan Cilt Tonu",
    desc: "Ton eşitleme teknikleri",
    difficulty: "Orta",
    duration: "8-10 dk",
    tools: ["Güzellik süngeri", "Renk düzeltici", "Fondöten"],
    steps: [
      { title: "Renk haritası çıkarın", detail: "Yüzünüzdeki farklı tonları belirleyin: kızarık, sarımsı, koyu lekeler gibi." },
      { title: "Bölgesel renk düzeltme yapın", detail: "Kızarıklık → yeşil, koyu lekeler → şeftali/turuncu, sarımsı ton → lavanta düzeltici." },
      { title: "Orta kapatıcılıkta fondöten uygulayın", detail: "Tek seferde tam kapatma yerine katman katman uygulayın. İhtiyaç olan bölgelere ekstra katman ekleyin." },
      { title: "Kapatıcı ile noktasal düzeltme", detail: "Fondöten sonrası hâlâ görünen lekelere kapatıcı ile noktasal müdahale yapın." },
      { title: "Pudra ve sprey ile sabitleyin", detail: "Hafif pudra + sabitleyici sprey kombinasyonu ile bitirin." },
    ],
    tips: [
      "SPF düzenli kullanım lekeleri önler",
      "Niacinamide serumu ton eşitsizliğini azaltır",
      "Fondöteni doğal ışıkta test edin",
    ],
    productTypes: ["Renk Düzeltici Set", "Orta Kapatıcı Fondöten", "Kapatıcı", "Sabitleyici"],
  },
  {
    slug: "ince-dudaklar",
    icon: "👄",
    title: "İnce Dudaklar",
    desc: "Dudakları dolgun gösterme",
    difficulty: "Kolay",
    duration: "3-5 dk",
    tools: ["Dudak kalemi", "Ruj", "Lip gloss"],
    steps: [
      { title: "Dudakları nemlendirin", detail: "Dudak peelingi veya balm ile dudakları yumuşatın. Pürüzsüz dudaklar dolgun görünür." },
      { title: "Dudak kalemi ile çerçeveleyin", detail: "Doğal dudak çizginizin 1mm dışından çizin. Daha fazlası yapay görünür. Ruj tonunuzla eşleşen kalem seçin." },
      { title: "İçini doldurun", detail: "Dudak kalemi ile dudağın içini tamamen doldurun. Bu ruj kalıcılığını artırır." },
      { title: "Ruj uygulayın", detail: "Kremsi veya saten bitişli ruj uygulayın. Mat ruj ince dudakları daha ince gösterir." },
      { title: "Gloss ile dolgunlaştırın", detail: "Dudağın ortasına şeffaf veya ışıltılı gloss uygulayın. Işık yansıması dolgunluk illüzyonu yaratır." },
    ],
    tips: [
      "Açık tonlar dudakları büyük, koyu tonlar küçük gösterir",
      "Dudağın ortasına açık ton uygulama dolgunluk verir",
      "Mentollü/biberli lip plumper geçici dolgunluk sağlar",
    ],
    productTypes: ["Dudak Kalemi", "Kremsi Ruj", "Lip Gloss", "Lip Plumper"],
  },
  // === YENİ ÇÖZÜMLER ===
  {
    slug: "smokey-eye",
    icon: "🌑",
    title: "Smokey Eye",
    desc: "Klasik dumanlı göz makyajı",
    difficulty: "İleri",
    duration: "15-20 dk",
    tools: ["Far paleti", "Yedirme fırçası", "Göz kalemi", "Maskara"],
    steps: [
      { title: "Göz kapağına primer uygulayın", detail: "Göz farı primeri makyajın kalıcılığını artırır ve renklerin canlı görünmesini sağlar." },
      { title: "Geçiş tonunu uygulayın", detail: "Orta tonlu mat bir far ile göz çukuruna geçiş tonu uygulayın. Bu derinlik yaratır." },
      { title: "Koyu tonu ekleyin", detail: "Koyu rengi göz kapağının dış köşesine ve alt kirpik dibine uygulayın. V şekli oluşturun." },
      { title: "İyice yedirin", detail: "Yedirme fırçası ile sınırları yumuşatın. Smokey eye'da sert çizgi olmamalı." },
      { title: "Aydınlık ton ekleyin", detail: "İç göz köşesine ve kaş altına açık ışıltılı ton uygulayın. Gözü açar." },
      { title: "Eyeliner ve maskara ile bitirin", detail: "Kirpik dibine siyah kalem çekin ve bol maskara uygulayın." },
    ],
    tips: [
      "Altına şeffaf pudra serpin, dökülen farı temizlemek kolay olur",
      "Kahverengi tonlar daha gündüz, siyah daha gece uygun",
      "Alt göz kapağını ihmal etmeyin, bütünlük sağlar",
    ],
    productTypes: ["Far Paleti", "Göz Farı Primeri", "Yedirme Fırçası", "Maskara"],
  },
  {
    slug: "dogal-no-makeup",
    icon: "🍃",
    title: "No-Makeup Makeup",
    desc: "Doğal ama bakımlı görünüm",
    difficulty: "Kolay",
    duration: "5-8 dk",
    tools: ["BB krem", "Kaş jeli", "Dudak balm", "Maskara"],
    steps: [
      { title: "Cildi iyi nemlendirin", detail: "İyi nemlenen cilt doğal makyajın temelidir. Serum + nemlendirici uygulayın." },
      { title: "BB krem veya tinted moisturizer sürün", detail: "Parmakla hafifçe yayarak doğal bir kaplama elde edin. Kapatıcılık düşük olmalı." },
      { title: "Kaşları şekillendirin", detail: "Şeffaf veya renkli kaş jeli ile kaşları doğal şekilde tarayın." },
      { title: "Yanakları renklendirin", detail: "Kremsi allık veya dudak-yanak ürünü ile yanakları hafifçe renklendirin." },
      { title: "Dudaklara renk verin", detail: "Renkli dudak balm veya lip tint ile doğal bir renk ekleyin." },
      { title: "Maskara sürün", detail: "Sadece üst kirpiklere bir kat kahverengi veya siyah maskara." },
    ],
    tips: [
      "Daha az ürün daha iyi sonuç verir",
      "Kremsi formüller toz ürünlere göre daha doğal durur",
      "Cilt bakımına yatırım yapın, az makyaj yeter",
    ],
    productTypes: ["BB Krem", "Kremsi Allık", "Kaş Jeli", "Lip Tint"],
  },
  {
    slug: "kas-sekillendirme",
    icon: "✏️",
    title: "Kaş Şekillendirme",
    desc: "Yüzü çerçeveleyen kaş teknikleri",
    difficulty: "Orta",
    duration: "5-10 dk",
    tools: ["Kaş kalemi", "Kaş fırçası", "Kaş jeli", "Kapatıcı"],
    steps: [
      { title: "Doğal kaş şeklinizi analiz edin", detail: "Burun kenarından düz çekilen çizgi kaşın başlangıcını, burun kenarından göz bebeği üzerinden çekilen çizgi tepesini, burun kenarından göz dış köşesinden çekilen çizgi bitişini belirler." },
      { title: "Boşlukları doldurun", detail: "İnce kaş kalemi ile tüy benzeri kısa çizgiler çekerek seyrek bölgeleri doldurun." },
      { title: "Fırça ile yedirin", detail: "Kaş fırçası (spoolie) ile rengi yedirip doğal bir geçiş oluşturun." },
      { title: "Kaş jeli ile sabitleyin", detail: "Şeffaf veya renkli kaş jeli ile kaşları yerinde tutun." },
      { title: "Kaş altını temizleyin", detail: "İnce kapatıcı fırçası ile kaş altına kapatıcı sürerek keskin ve temiz bir hat oluşturun." },
    ],
    tips: [
      "Saç renginizden 1-2 ton açık kaş ürünü daha doğal durur",
      "Kaşın başını asla çok keskin yapmayın, yumuşak bırakın",
      "Sabun kaş tekniği dolgun görünüm için mükemmel",
    ],
    productTypes: ["Kaş Kalemi", "Kaş Jeli", "Kaş Pomadı", "Kaş Fırçası"],
  },
  {
    slug: "eyeliner-teknikleri",
    icon: "🖊️",
    title: "Eyeliner Çekme",
    desc: "Mükemmel eyeliner teknikleri",
    difficulty: "İleri",
    duration: "5-10 dk",
    tools: ["Likit eyeliner", "Kalem eyeliner", "Bant", "Misel su"],
    steps: [
      { title: "Göz şeklinizi belirleyin", detail: "Badem, yuvarlak, kapak düşüklüğü, tek kapak: her göz şekline farklı eyeliner tekniği uyar." },
      { title: "Kuyruk açısını belirleyin", detail: "Alt kirpik çizgisinin devamı yönünde kuyruk çizin. Bant yapıştırarak rehber oluşturabilirsiniz." },
      { title: "İnce bir çizgiyle başlayın", detail: "Göz ortasından dışa doğru ince bir çizgi çekin. Kalınlığı sonra artırabilirsiniz." },
      { title: "İç köşeye doğru tamamlayın", detail: "Göz ortasından iç köşeye doğru incelerek çizgiyi tamamlayın." },
      { title: "Hataları düzeltin", detail: "Pamuklu çubuk ve misel su ile hataları temizleyin. Kapatıcı ile de düzeltebilirsiniz." },
    ],
    tips: [
      "Likit eyeliner keskin hat, kalem eyeliner yumuşak hat verir",
      "Gözü açık tutarak çizin, kapalı gözde hat farklı görünür",
      "Acemiyseniz kalem eyelinerla başlayın, affedicidir",
    ],
    productTypes: ["Likit Eyeliner", "Kalem Eyeliner", "Jel Eyeliner", "Misel Su"],
  },
  {
    slug: "allik-uygulama",
    icon: "🌸",
    title: "Allık Uygulama",
    desc: "Yüz şekline göre allık teknikleri",
    difficulty: "Kolay",
    duration: "2-5 dk",
    tools: ["Allık fırçası", "Allık", "Güzellik süngeri"],
    steps: [
      { title: "Yüz şeklinizi belirleyin", detail: "Yuvarlak yüz: elmacık kemikleri boyunca yukarı. Uzun yüz: yanaklara yatay. Kalp yüz: elmacıkların altına." },
      { title: "Gülümseyin ve uygulayın", detail: "Gülümsediğinizde belirginleşen yanak toplarına uygulayın." },
      { title: "Yedirin", detail: "Fırça veya sünger ile sınırları yumuşatın. Sert renk geçişi olmamalı." },
      { title: "Katman ekleyin", detail: "Az ürünle başlayıp gerekirse katman ekleyin. Fazla allığı temizlemek zordur." },
    ],
    tips: [
      "Toz allık yağlı ciltlere, krem allık kuru ciltlere uygun",
      "Bronzer ile allığı karıştırmak doğal güneş öpmüş etki yaratır",
      "Allık rengini dudak rengine yakın seçin, uyumlu görünür",
    ],
    productTypes: ["Toz Allık", "Krem Allık", "Allık Paleti", "Allık Fırçası"],
  },
  {
    slug: "goz-fari-baslangic",
    icon: "🎨",
    title: "Göz Farı Başlangıç",
    desc: "Temel göz farı uygulama rehberi",
    difficulty: "Kolay",
    duration: "5-10 dk",
    tools: ["Far paleti", "Düz fırça", "Yedirme fırçası", "Far primeri"],
    steps: [
      { title: "Far primeri uygulayın", detail: "Göz kapağına ince bir tabaka primer sürün. Farın kalıcılığını 2-3 kat artırır." },
      { title: "Açık tonu tüm kapağa sürün", detail: "Bej veya şampanya tonlu far ile tüm göz kapağını kaplayın. Bu baz görevi görür." },
      { title: "Orta tonu göz çukuruna uygulayın", detail: "Yedirme fırçası ile göz çukuruna orta tonlu far uygulayın. Derinlik yaratır." },
      { title: "Koyu tonu dış köşeye ekleyin", detail: "Dış V bölgesine koyu ton uygulayıp yedirin." },
      { title: "Işıltıyı iç köşeye ve kapak ortasına ekleyin", detail: "Parlak veya simli far ile iç köşeyi ve kapak merkezini aydınlatın." },
    ],
    tips: [
      "3 tonlu palet başlangıç için yeterli: açık, orta, koyu",
      "Yedirme en önemli adımdır, sert geçiş olmamalı",
      "Mat tonlar gündüz, simli tonlar gece için ideal",
    ],
    productTypes: ["Far Paleti", "Far Primeri", "Far Fırça Seti", "Göz Kalemi"],
  },
  {
    slug: "bronzlasma-efekti",
    icon: "☀️",
    title: "Bronzlaşma Efekti",
    desc: "Güneşten öpülmüş doğal görünüm",
    difficulty: "Kolay",
    duration: "5-8 dk",
    tools: ["Bronzer", "Büyük fırça", "Highlighter"],
    steps: [
      { title: "Doğru bronzer tonu seçin", detail: "Cildinizden 1-2 ton koyu, sıcak tonlu bronzer seçin. Çok koyu bronzer çamurlu görünür." },
      { title: "3 bölgeye uygulayın", detail: "Güneşin doğal vurduğu yerler: alın kenarları, elmacık kemikleri altı ve çene hattı." },
      { title: "Boynunuza da sürün", detail: "Yüz-boyun uyumu için bronzeri boyun ve dekolteye de hafifçe uygulayın." },
      { title: "Highlighter ekleyin", detail: "Elmacık kemiklerinin tepesine, burun sırtına ve üst dudak ortasına highlighter sürün." },
    ],
    tips: [
      "Mat bronzer daha doğal, simli bronzer daha glamuröz",
      "Hafif katmanlar halinde uygulayın, fazlasını almak zordur",
      "Kış aylarında 1 ton açık bronzer tercih edin",
    ],
    productTypes: ["Bronzer", "Highlighter", "Büyük Pudra Fırçası", "Bronzlaştırıcı Damla"],
  },
  {
    slug: "kirpik-bakim",
    icon: "👁️‍🗨️",
    title: "Kirpik Teknikleri",
    desc: "Hacimli ve uzun kirpik sırları",
    difficulty: "Kolay",
    duration: "3-5 dk",
    tools: ["Maskara", "Kirpik kıvırıcı", "Kirpik primeri"],
    steps: [
      { title: "Kirpikleri kıvırın", detail: "Kirpik kıvırıcı ile kök, orta ve uç olmak üzere 3 noktada bastırın. Maskaradan ÖNCE kıvırın." },
      { title: "Kirpik primeri uygulayın", detail: "Beyaz kirpik primeri hacim ve uzunluk ekler. Kurumadan maskara uygulayın." },
      { title: "Maskarayı zigzag hareketle sürün", detail: "Kökten uca zigzag yaparak sürün. Bu kirpikleri ayırır ve hacim verir." },
      { title: "Alt kirpiklere dikkat edin", detail: "Alt kirpiklere fırçayı dikey tutarak hafifçe sürün. Dağılmayı önler." },
    ],
    tips: [
      "Waterproof maskara kıvrımı daha uzun tutar",
      "İkinci kat maskarayı ilk kat kurumadan sürün",
      "Baby powder ile katmanlar arasına uygulama ekstra hacim verir",
    ],
    productTypes: ["Hacim Maskarası", "Uzatıcı Maskara", "Kirpik Kıvırıcı", "Kirpik Primeri"],
  },
  {
    slug: "yaglanma-kontrolu",
    icon: "💧",
    title: "Yağlanma Kontrolü",
    desc: "Gün boyu mat kalma teknikleri",
    difficulty: "Kolay",
    duration: "5-8 dk",
    tools: ["Matlaştırıcı primer", "Pudra", "Yağ emici kağıt"],
    steps: [
      { title: "Cildi hafif nemlendirin", detail: "Yağsız, jel formlu nemlendirici kullanın. Nemlendirilmeyen yağlı cilt daha çok yağ üretir." },
      { title: "Matlaştırıcı primer uygulayın", detail: "T bölgesine (alın, burun, çene) matlaştırıcı primer uygulayın." },
      { title: "Yağsız fondöten seçin", detail: "Oil-free, mat bitişli fondöten kullanın. Güzellik süngeri ile yedirin." },
      { title: "Pudra ile sabitleyin", detail: "Transparan pudrayı T bölgesine hafifçe uygulayın. Aşırı pudra cake face yapar." },
      { title: "Gün içi bakım yapın", detail: "Yağ emici kağıtlar ile gün içi yağı bastırarak alın. Pudra eklemek yerine bunu tercih edin." },
    ],
    tips: [
      "Niacinamide serumu uzun vadede yağlanmayı azaltır",
      "Sabitleyici sprey pudra sonrası kalıcılığı artırır",
      "Makyaj üstü SPF spreyi kullanarak hem koruyun hem matlaştırın",
    ],
    productTypes: ["Matlaştırıcı Primer", "Oil-free Fondöten", "Transparan Pudra", "Yağ Emici Kağıt"],
  },
  {
    slug: "gelinlik-makyaji",
    icon: "💍",
    title: "Gelin Makyajı",
    desc: "Uzun süre dayanan özel gün makyajı",
    difficulty: "İleri",
    duration: "30-45 dk",
    tools: ["Tam fırça seti", "Güzellik süngeri", "Sabitleyici sprey", "Takma kirpik"],
    steps: [
      { title: "Cildi önceden hazırlayın", detail: "Düğünden 1 hafta önce peeling, 1 gün önce nemlendirici maske yapın." },
      { title: "Uzun ömürlü baz oluşturun", detail: "Primer + uzun süre kalıcı fondöten + kapatıcı + pudra ile sağlam baz oluşturun." },
      { title: "Göz makyajını yapın", detail: "Waterproof ürünlerle göz makyajı yapın. Nötr ve romantik tonlar tercih edin." },
      { title: "Kontur ve aydınlatma", detail: "Hafif kontur ile yüzü şekillendirin, ışıltılı highlighter ile parlatın." },
      { title: "Dudak ve allık", detail: "Kalıcı ruj + dudak kalemi kombinasyonu. Allığı hafif ve romantik tutun." },
      { title: "Sabitleyici ile kilitleyin", detail: "Katman katman sabitleyici sprey uygulayın. Her aşamada spreyleyebilirsiniz." },
    ],
    tips: [
      "Düğün öncesi mutlaka deneme makyajı yapın",
      "Fotoğrafta beyaz yansıma yapan SPF ürünlerden kaçının",
      "Rötuş çantası hazırlayın: ruj, pudra, yağ emici kağıt, sabitleyici",
    ],
    productTypes: ["Kalıcı Fondöten", "Waterproof Maskara", "Sabitleyici Sprey", "Takma Kirpik"],
  },
  {
    slug: "ten-rengi-eslesme",
    icon: "🎯",
    title: "Fondöten Renk Eşleşme",
    desc: "Doğru fondöten tonu bulma rehberi",
    difficulty: "Kolay",
    duration: "5-10 dk",
    tools: ["Fondöten örnekleri", "Doğal ışık"],
    steps: [
      { title: "Alt tonunuzu belirleyin", detail: "Bileklerinizin iç kısmına bakın: mavi damarlar = soğuk, yeşil damarlar = sıcak, karışık = nötr alt ton." },
      { title: "Çene hattında test edin", detail: "Fondöteni yüzünüze değil, çene hattına sürün. Yüz genelde boyundan farklı tondadır." },
      { title: "Doğal ışıkta kontrol edin", detail: "Mağazadaki yapay ışık yanıltır. Pencere kenarına veya dışarı çıkıp kontrol edin." },
      { title: "3 ton test edin", detail: "Tahmini tonunuz + 1 ton açık + 1 ton koyu deneyip en iyi eşleşeni seçin." },
      { title: "Boyunla uyumu kontrol edin", detail: "Doğru ton boyunla bütünleşir, yüzde maske etkisi yaratmaz." },
    ],
    tips: [
      "Yaz ve kış için 2 farklı ton fondöten bulundurun",
      "Mevsim geçişlerinde iki tonu karıştırarak kullanın",
      "Online alışverişte iade politikasını kontrol edin",
    ],
    productTypes: ["Fondöten", "BB Krem", "CC Krem", "Tinted Moisturizer"],
  },
  {
    slug: "dudak-bakimi",
    icon: "💋",
    title: "Dudak Bakımı & Makyaj",
    desc: "Kalıcı ve güzel dudak makyajı",
    difficulty: "Kolay",
    duration: "3-5 dk",
    tools: ["Dudak peeling", "Dudak kalemi", "Ruj", "Kağıt mendil"],
    steps: [
      { title: "Dudakları peelinleyin", detail: "Şeker + bal karışımı veya dudak scrub ile ölü derileri temizleyin." },
      { title: "Nemlendirin", detail: "Dudak balm ile 5 dakika nemlendirin. Ruj öncesi silin." },
      { title: "Dudak kalemi ile çerçeveleyin", detail: "Ruj tonuna yakın dudak kalemi ile dudakları çerçeveleyin ve içini doldurun." },
      { title: "Ruj uygulayın", detail: "Fırça veya doğrudan ruj uygulayın." },
      { title: "Kağıt mendil tekniği", detail: "Bir kat ruj → kağıt mendil bastırın → ikinci kat ruj. Bu kalıcılığı 2 katına çıkarır." },
    ],
    tips: [
      "Mat rujlar daha kalıcı ama kurutucu, üstüne balm sürün",
      "Dudak çevresine kapatıcı sürme ruj dağılmasını önler",
      "Kırmızı ruj mavi alt tonlu ciltlere, turuncu kırmızı sıcak alt tonlara uyar",
    ],
    productTypes: ["Dudak Peeling", "Dudak Kalemi", "Mat Ruj", "Lip Stain"],
  },
  {
    slug: "hassas-cilt-makyaji",
    icon: "🧴",
    title: "Hassas Cilt Makyajı",
    desc: "Tahriş etmeyen makyaj seçimleri",
    difficulty: "Orta",
    duration: "10-15 dk",
    tools: ["Mineral makyaj ürünleri", "Yumuşak fırçalar", "Termal su"],
    steps: [
      { title: "Cildi yatıştırın", detail: "Centella veya aloe vera içeren nemlendirici uygulayın. Tahriş eden aktiflerden kaçının." },
      { title: "Hassas cilt primeri kullanın", detail: "Parfümsüz, silikon bazlı primer ile koruyucu bariyer oluşturun." },
      { title: "Mineral fondöten tercih edin", detail: "Mineral fondöten kimyasal katkısız olduğu için hassas ciltlere uygun. Fiziksel SPF de içerir." },
      { title: "Minimal ürün kullanın", detail: "Ne kadar az ürün, o kadar az tahriş riski. Sadece gerekli ürünleri uygulayın." },
      { title: "Termal su ile bitirin", detail: "Sabitleyici sprey yerine termal su spreyi ile makyajı ferahlatın." },
    ],
    tips: [
      "Yeni ürünleri kulak arkasında test edin, 24 saat bekleyin",
      "Parfümsüz ve hipoalerjenik ürünler tercih edin",
      "Makyaj fırçalarını haftada 1 yıkayın, bakteri birikimini önleyin",
    ],
    productTypes: ["Mineral Fondöten", "Hassas Cilt Primeri", "Termal Su", "Hipoalerjenik Maskara"],
  },
  {
    slug: "goz-kapagi-dusukluğu",
    icon: "👀",
    title: "Göz Kapağı Düşüklüğü",
    desc: "Kapak düşüklüğüne uygun göz makyajı",
    difficulty: "Orta",
    duration: "8-12 dk",
    tools: ["Far paleti", "Eyeliner", "Kirpik kıvırıcı", "Maskara"],
    steps: [
      { title: "Kapağı katlayarak çalışın", detail: "Gözler açıkken göz çukuru çizgisinin üstüne renk koyun. Kapalı gözde yapılan makyaj kapak arkasında kaybolur." },
      { title: "Koyu tonu doğru yerleştirin", detail: "Koyu far göz çukuru çizgisinin biraz üstüne uygulayın. Göz açıkken görünmeli." },
      { title: "Eyeliner tekniği", detail: "İnce eyeliner kullanın, kalın eyeliner kapağı daha düşük gösterir. Kuyrukta yukarı doğru çekin." },
      { title: "Kirpiklere odaklanın", detail: "Kirpik kıvırıcı + 2 kat maskara. Üst kirpikler yukarı baktığında göz açılır." },
      { title: "Kaş altını aydınlatın", detail: "Kaş kemiğinin altına mat açık far uygulayarak göz kapağını kaldırma illüzyonu yaratın." },
    ],
    tips: [
      "Waterproof formüller kapak katlanmasıyla bulaşmaz",
      "Alt göz kapağına koyu ton uygulamayın, gözü küçültür",
      "Takma kirpikler göz kapağını kaldırma etkisi yaratır",
    ],
    productTypes: ["Mat Far Paleti", "İnce Eyeliner", "Waterproof Maskara", "Kirpik Kıvırıcı"],
  },
  {
    slug: "makyaj-sabitleme",
    icon: "🔒",
    title: "Makyaj Sabitleme",
    desc: "12+ saat kalıcı makyaj teknikleri",
    difficulty: "Kolay",
    duration: "3-5 dk",
    tools: ["Primer", "Sabitleyici pudra", "Sabitleyici sprey"],
    steps: [
      { title: "Doğru primer seçin", detail: "Yağlı cilt: matlaştırıcı primer. Kuru cilt: nemlendirici primer. Primer fondötenin tutunmasını sağlar." },
      { title: "İnce katmanlar halinde uygulayın", detail: "Kalın makyaj katmanları kayar. İnce katmanlar + aralarında sabitleme = kalıcı makyaj." },
      { title: "Stratejik pudralayın", detail: "Pudrayı sadece T bölgesine uygulayın. Tüm yüze pudra cake face yapar." },
      { title: "Sabitleyici sprey kullanın", detail: "Son dokunuş olarak sabitleyici sprey. Yüzden 20cm uzaktan X şeklinde sıkın." },
      { title: "Gün içi rötuş yapın", detail: "Yağ emici kağıt + sabitleyici sprey ile gün içi tazeleyin. Üstüne makyaj eklemeyin." },
    ],
    tips: [
      "Baking tekniği: pudrayı 5 dk bekletip silmek ekstra kalıcılık verir",
      "Sabitleyici sprey buzdolabında saklayın, serinliği gözenekleri sıkılaştırır",
      "Yaz aylarında waterproof ürünler şart",
    ],
    productTypes: ["Sabitleyici Sprey", "Transparan Pudra", "Matlaştırıcı Primer", "Yağ Emici Kağıt"],
  },
];
